---

version: 0.2

env:
  shell: bash
  variables:
    DOCKER_BUILDKIT: 1
  parameter-store:
    GITHUB_ACCESS_TOKEN: '/strongpool/_/_/build/github-access-token'
  exported-variables:
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - dockerd-entrypoint.sh &
      - until docker info >/dev/null 2>&1; do sleep 1; done
      - echo $GITHUB_ACCESS_TOKEN | docker login ghcr.io -u strongpool-builds --password-stdin
      - IMAGE_TAG="$(cat RELEASE_NUMBER)-strongpool-$(voom-like-version)"
      - git submodule update --init --recursive

  build:
    commands:
      - ./build/build

cache:
  paths:
    - '/root/last-success-version'
