#!/usr/bin/env bash

set -e

[ -n "$DEBUG" ] && set -x

if [ -n "$INGRESS_RATE" ]; then
    tc qdisc add dev eth0 handle 1: ingress
    tc filter add dev eth0 parent 1: protocol ip prio 50 u32 match ip src 0.0.0.0/0 police rate "${INGRESS_RATE}" burst 10k drop flowid :1
fi

if [ -n "$EGRESS_RATE" ]; then
    tc qdisc add dev eth0 root tbf rate "${EGRESS_RATE}" latency 100ms burst 10k
fi

cd /arweave

./erts-11.2.2.3/bin/epmd -daemon

./bin/start data_dir /data "$@"
