---

name: Build
on: [push]
  push:
    branches:
      - github-workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ##
      ## Start notification
      ##

      - name: Notify Slack start
        uses: voxmedia/github-action-slack-notify-build@v1
        id: slack
        with:
          channel: dev-log
          status: STARTING
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}

      ##
      ## Checkout repo
      ##

      - name: Checkout repo
        uses: actions/checkout@v2

      ##
      ## Setup
      ##

      - name: Install Ubuntu packages
        run: sudo apt-get install -y build-essential cmake git libgmp-dev libsqlite3-dev

      # TODO shellcheck and yamllint?

      ##
      ## Lint steps
      ##

      # TODO shellcheck and yamllint?

      ##
      ## Test steps
      ##

      - name: Run tests
        run: ./bin/test

      ##
      ## Slack completion notifications
      ##

      # Updates existing message from the first step
      - name: Notify Slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: dev-log
          status: SUCCESS
          color: good

      # Updates existing message from the first step
      - name: Notify Slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: dev-log
          status: FAILED
          color: danger

      # For notification purposes, sends to a separate channel on failure
      - name: Notify Slack failure (build failures channel)
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: build-failures
          status: FAILED
          color: danger

      ##
      ## Discord completion notifications
      ##

      - name: Notify Discord failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build failed!
          webhookUrl: ${{ secrets.DISCORD_DEV_LOG_WEBHOOK }}

      - name: Notify Discord canceled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Build canceled!
          webhookUrl: ${{ secrets.DISCORD_DEV_LOG_WEBHOOK }}
